# Generated by Django 6.0.2 on 2026-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='polls_choices',
            field=models.ManyToManyField(default=None, to='polls.choice'),
        ),
    ]
