# Generated by Django 6.0.2 on 2026-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_polls_choices'),
        ('polls', '0004_remove_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='polls_choices',
            field=models.ManyToManyField(to='polls.choice'),
        ),
    ]
