# Generated by Django 6.0.2 on 2026-03-23 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='author',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 23, 18, 0, 50, 123431, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
